server:
  port: 8080


#配置redis信息
spring:
  redis:
    host: 192.168.28.129
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/redisdemo?useUnicode=true&characterEncoding=utf8
    username: root
    password: mi12345678
    type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个

    druid:
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 1000

#mybatis配置
mybatis:
  #pojo别名扫描包
  type-aliases-package: com.laoli.commons.beans
  #加载Mybatis映射文件
  mapper-locations: classpath:mybatisMapper/*.xml
  #开启驼峰命名规则
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.laoli.redisDemo.dao: debug
#调整日志级别